name: /om2/user/sitzmann/lf
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - anyio=2.2.0=py36h5fab9bb_0
  - argon2-cffi=20.1.0=py36h8f6f2f9_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py36h8f6f2f9_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.5=py36hc120d54_0
  - chardet=4.0.0=py36h5fab9bb_1
  - cloudpickle=1.6.0=py_0
  - configargparse=1.2.3=py_0
  - contextvars=2.4=py_0
  - cryptography=3.4.6=py36hb60f036_0
  - cudatoolkit=11.1.1=h6406543_8
  - curl=7.77.0=hea6ffbf_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh787bdff_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py36h5fab9bb_3
  - geos=3.8.0=he6710b0_0
  - glib=2.67.4=h36276a3_1
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - immutables=0.15=py36h8f6f2f9_0
  - ipykernel=5.5.0=py36he448a4c_1
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py36h5fab9bb_0
  - jupyter_server=1.4.1=py36h5fab9bb_0
  - jupyterlab=3.0.14=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py36h2531618_0
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libcurl=7.77.0=h2574ce0_0
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - liblapack=3.9.0=8_mkl
  - libnghttp2=1.43.0=h812cca2_0
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.5=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.41.0=h7f98852_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=11.0.1=h4bd325d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py36h8f6f2f9_3
  - matplotlib=3.3.4=py36h06a4308_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mistune=0.8.4=py36h8f6f2f9_1003
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py36he8ac12f_0
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36h5fab9bb_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - ninja=1.10.2=h4bd325d_0
  - nodejs=12.4.0=he1b5a44_0
  - notebook=6.2.0=py36h5fab9bb_0
  - numpy=1.19.5=py36h2aa4a07_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=3.4.2=py36h6fd60c2_1
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.1.5=py36ha9443f7_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py36ha6010c0_0
  - pip=21.0.1=py36h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - plotly=4.14.3=py_0
  - poppler=0.90.1=h4190859_0
  - poppler-data=0.4.10=0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h8f6f2f9_2
  - pysocks=1.7.1=py36h5fab9bb_3
  - python=3.6.13=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.8.0=py3.6_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.4.1=py36h27cfd23_1
  - pyzmq=22.0.3=py36h7068817_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - retrying=1.3.3=py36_2
  - scikit-image=0.17.2=py36hdf5156a_0
  - scipy=1.5.2=py36h0b6359f_0
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py36h06a4308_0
  - shapely=1.7.1=py36h98ec03d_0
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=pyh9f0ad1d_0
  - sleef=3.5.1=h7f98852_1
  - sniffio=1.2.0=py36h5fab9bb_1
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.3=py36h5fab9bb_0
  - testpath=0.4.4=py_0
  - tifffile=2020.10.1=py36hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchaudio=0.8.0=py36
  - torchvision=0.2.2=py_3
  - tornado=6.1=py36h27cfd23_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==0.11.0
    - cachetools==4.2.1
    - google-auth==1.27.1
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - imageio-ffmpeg==0.4.3
    - importlib-metadata==3.7.2
    - ipympl==0.7.0
    - markdown==3.3.4
    - moviepy==1.0.3
    - oauthlib==3.1.0
    - ordered-set==4.0.2
    - pdf2image==1.15.1
    - proglog==0.1.9
    - protobuf==3.15.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - urllib3==1.26.3
    - werkzeug==1.0.1
prefix: /om2/user/sitzmann/lf
