name: lf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.12.0=py36h06a4308_0
  - aiohttp=3.7.4=py36h27cfd23_1
  - async-timeout=3.0.1=py36h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - blinker=1.4=py36h06a4308_0
  - brotlipy=0.7.0=py36h27cfd23_1003
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.5.25=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.5=py36h261ae71_0
  - chardet=3.0.4=py36h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - configargparse=1.4=pyhd3eb1b0_0
  - coverage=5.5=py36h27cfd23_2
  - cryptography=2.9.2=py36h1ba5d50_0
  - cycler=0.10.0=py36_0
  - cython=0.29.23=py36h2531618_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.2.1=h58526e2_0
  - freetype=2.10.4=h7ca028e_0
  - glib=2.68.2=h36276a3_0
  - google-auth=1.30.1=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.36.1=py36h2157cd5_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyhd3eb1b0_0
  - idna_ssl=1.1.0=py36h06a4308_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py36h06a4308_0
  - jasper=2.0.14=habb8e15_1
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py36h2531618_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglu=9.0.0=he1b5a44_1001
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.9=h648cc4a_1002
  - libuuid=2.32.1=h14c3975_1000
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - markdown=3.3.4=py36h06a4308_0
  - matplotlib-base=3.2.2=py36hef1b27d_0
  - multidict=5.1.0=py36h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - numpy=1.19.4=py36h8732dcd_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.44=he1b5a44_0
  - pip=21.1.1=py36h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - protobuf=3.14.0=py36h2531618_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=3.4.2=py36hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=2.1.0=py36h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.13=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.6=1_cp36m
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.4.1=py36h27cfd23_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.17.2=py36hdf5156a_0
  - scipy=1.5.2=py36habc2bb6_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tensorboard=2.5.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tifffile=2020.10.1=py36hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py36h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py36h27cfd23_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - dataclasses==0.8
    - ordered-set==4.0.2
    - pillow==8.2.0
    - torch==1.8.1+cpu
    - torchvision==0.9.1+cpu
    - typing-extensions==3.10.0.0
prefix: /home/sitzmann/anaconda3/envs/lf
